name: klib_env
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appdirs=1.4.3
  - astroid=2.3.3
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - autopep8=1.5.2
  - babel=2.8.0
  - backcall=0.1.0
  - bandit=1.6.2
  - beautifulsoup4=4.9.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cmarkgfm=0.4.2
  - colorama=0.4.3
  - conda-package-handling=1.6.0
  - console_shortcut=0.1.1
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - filelock=3.0.10
  - flake8=3.7.9
  - freetype=2.10.1
  - future=0.18.2
  - gitdb=4.0.5
  - gitpython=3.1.3
  - glob2=0.7
  - icc_rt=2019.0.0
  - icu=64.2
  - idna=2.9
  - imagesize=1.2.0
  - imbalanced-learn=0.6.2
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.0
  - ipykernel=5.2.1
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jdcal=1.4.1
  - jedi=0.15.2
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9c
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=2.1.2
  - jupyterlab_server=1.1.1
  - keyring=21.1.1
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblief=0.9.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - libxml2=2.9.10
  - llvmlite=0.31.0
  - lz4-c=1.9.2
  - lzo=2.10
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mccabe=0.6.1
  - menuinst=1.4.16
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - more-itertools=8.2.0
  - msys2-conda-epoch=20160418
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - nodejs=13.13.0
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.5
  - numpydoc=1.1.0
  - openpyxl=3.0.3
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathspec=0.8.0
  - patsy=0.5.1
  - pbr=5.4.5
  - pickleshare=0.7.5
  - pip=20.1
  - pkginfo=1.5.0.1
  - pluggy=0.13.0
  - pockets=0.9.1
  - powershell_shortcut=0.0.1
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - psutil=5.7.0
  - py=1.8.1
  - py-lief=0.9.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pydocstyle=5.0.2
  - pyflakes=2.1.1
  - pygments=2.6.1
  - pylint=2.4.4
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.10
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytz=2020.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.0
  - qt=5.12.5
  - readme_renderer=24.0
  - regex=2020.6.8
  - requests=2.23.0
  - requests-toolbelt=0.9.1
  - ripgrep=12.0.1
  - rope=0.16.0
  - rstcheck=3.3.1
  - ruamel_yaml=0.15.80
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - smmap=3.0.4
  - snowballstemmer=2.0.0
  - soupsieve=1.9.4
  - sphinx=3.1.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - stevedore=2.0.1
  - terminado=0.8.3
  - testpath=0.4.4
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.45.0
  - traitlets=4.3.3
  - twine=3.1.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - ujson=1.35
  - urllib3=1.25.9
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.4
  - yapf=0.29.0
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - jupyter-lsp==0.8.0
    - klib==0.0.89
    - ppscore==0.0.2
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
