name: klib_env
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appdirs=1.4.3
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - autopep8=1.5.4
  - babel=2.8.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bandit=1.6.2
  - beautifulsoup4=4.9.1
  - black=19.10b0
  - blas=1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.1
  - cfgv=3.2.0
  - chardet=3.0.4
  - click=7.1.2
  - cmarkgfm=0.4.2
  - colorama=0.4.3
  - conda-package-handling=1.6.1
  - console_shortcut=0.1.1
  - coverage=5.2.1
  - cryptography=3.0
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distlib=0.3.1
  - docutils=0.16
  - editdistance=0.5.3
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - filelock=3.0.12
  - flake8=3.8.3
  - freetype=2.10.2
  - fribidi=1.0.10
  - future=0.18.2
  - gdk-pixbuf=2.38.2
  - gettext=0.19.8.1
  - gitdb=4.0.5
  - gitpython=3.1.3
  - glib=2.65.0
  - glob2=0.7
  - gobject-introspection=1.64.1
  - icc_rt=2019.0.0
  - icu=64.2
  - identify=1.4.25
  - idna=2.10
  - imagesize=1.2.0
  - imbalanced-learn=0.7.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - iniconfig=1.0.1
  - intel-openmp=2020.1
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - jupyterlab=2.2.2
  - jupyterlab_server=1.2.0
  - keyring=21.2.1
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libarchive=3.4.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcroco=0.6.13
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblief=0.10.1
  - libpng=1.6.37
  - librsvg=2.49.3
  - libsodium=1.0.17
  - libtiff=4.1.0
  - libxml2=2.9.10
  - llvmlite=0.33.0
  - lz4-c=1.9.2
  - lzo=2.10
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.0
  - matplotlib-base=3.3.0
  - mccabe=0.6.1
  - menuinst=1.4.16
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - more-itertools=8.4.0
  - msys2-conda-epoch=20160418
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - nodeenv=1.4.0
  - nodejs=14.7.0
  - notebook=6.1.0
  - numba=0.50.1
  - numpy=1.19.1
  - numpydoc=1.1.0
  - olefile=0.46
  - openpyxl=3.0.4
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.0
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.1
  - pathspec=0.8.0
  - patsy=0.5.1
  - pbr=5.4.5
  - pcre=8.44
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - pockets=0.9.1
  - powershell_shortcut=0.0.1
  - pre-commit=2.6.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - psutil=5.7.2
  - py=1.9.0
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pydocstyle=5.0.2
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pylint=2.5.3
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=6.0.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.34.1
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytz=2020.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.12.5
  - readme_renderer=24.0
  - regex=2020.7.14
  - requests=2.24.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.4.0
  - ripgrep=12.1.1
  - rope=0.17.0
  - rstcheck=3.3.1
  - ruamel_yaml=0.15.87
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - seaborn-base=0.10.1
  - send2trash=1.5.0
  - setuptools=49.2.1
  - six=1.15.0
  - smmap=3.0.4
  - snowballstemmer=2.0.0
  - soupsieve=2.0.1
  - sphinx=3.1.2
  - sphinx_rtd_theme=0.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.32.3
  - statsmodels=0.11.1
  - stevedore=3.2.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.48.0
  - traitlets=4.3.3
  - twine=3.2.0
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - ujson=1.35
  - urllib3=1.25.10
  - vc=14.1
  - virtualenv=20.0.20
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - jupyter-lsp==0.8.0
    - klib==0.1.1
    - ppscore==0.0.2
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - sphinxcontrib-svg2pdfconverter==1.1.0
