name: Black Code Formatter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      uses: lgeiger/black-action@v1.0.1
      with:
        args: --line-length 110
